### ISSUE TITLE
error parsing regexp: invalid escape sequence: `\1`

### ISSUE THREAD

**Issue by ghost** [itchyny/rassemble-go#1]
Hi,

I'm using yout tool to assemble PCRE regexes in alternative to "Regexp::Assemble".

Great job ! I look for the code of Regexp::Assemble, in the first line I saw a regex which parse regexes, and I close my text editor ;-)

I got this error:

```
rassemble: error parsing regexp: invalid escape sequence: `\1`
```

But, the \1 is a valid token, regex101 said: "matches the same text as most recently matched by the 1st capturing group". I check also in PCRE reference, and the doc confirm that backreference could be used in the match part.

**Comment by itchyny** [comment]
Instead of implementing the regex parser from scratch which is a tough work, this library uses the [regexp/syntax library](https://golang.org/pkg/regexp/syntax/). Even with [syntax.Perl flag](https://golang.org/pkg/regexp/syntax/#Flags), [the library does not support a backreference](https://github.com/golang/go/blob/go1.15.6/src/regexp/syntax/parse.go#L1261). Thus this is unfortunately not an issue of this library.
```go
package main

import (
	"fmt"
	"os"
	"regexp/syntax"
)

func main() {
	re, err := syntax.Parse(`(.)\1`, syntax.Perl)
	if err != nil {
		fmt.Printf("%v\n", err)
		os.Exit(1)
	}
	fmt.Printf("%v\n", re)
}
```
```
error parsing regexp: invalid escape sequence: `\1`
```

**Comment by ghost** [comment]
I understand. It is sad.
Thanks.
Thierry

**Comment by itchyny** [comment]
I found [regexp2](https://github.com/dlclark/regexp2) project which supports back reference. I rather prefer using the standard library but this is open source. It's worth trying switching to the regexp2 library. Closing as there is no action to take in the short term.
